version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: rails server -p 3000 -b 0.0.0.0
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - 3000:3000
  db:
    env_file:
      - .env
    image: postgres:11
    ports:
      - 5432:5432
